version: '3.8'

services:
  # 1. Contenedor del Sistema de Pedidos (Frontend y Backend)
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Variables de conexión a la BD (coinciden con config/db.ts)
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password_secreto
      - DB_NAME=restaurante_bd
      - DB_PORT=5432
      # Clave secreta para JWT (US010.2)
      - JWT_SECRET=clave_jwt_restaurante_eq3_2026
    depends_on:
      db:
        condition: service_healthy

  # 2. Contenedor de la Base de Datos (Persistencia)
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password_secreto
      - POSTGRES_DB=restaurante_bd
    volumes:
      # Persistencia de datos
      - pg_data:/var/lib/postgresql/data
      # Autocarga del esquema — :z para SELinux
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurante_bd"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  pg_data:
